#!/usr/bin/env python3
"""Offline bbox-label preprocessing for the LIBERO FastWAM dataset.

This bbox-only preprocessor keeps the ATM bbox label behavior, but all runtime
dependencies it needs are local to this FastWAM repository:

1. Task prompts come from `scripts/atm_bbox_prompts.py`.
2. Bboxes are generated by the local torch-2.7-patched GroundingDINO copy under
   `third_party/grounding_dino_torch27`.
3. The output cache stores only raw `[x1, y1, x2, y2]` boxes, confidences, and
   label strings. It does not compute any other auxiliary labels.

The produced `.npz` cache stores episode-level ragged bbox labels with offsets:

    bbox_xyxy: [K, 4]
    bbox_confidences: [K]
    bbox_offsets: [C, T + 1]

For camera `c` and labeled frame index `t`, use:

    start = bbox_offsets[c, t]
    end = bbox_offsets[c, t + 1]
    boxes = bbox_xyxy[start:end]
    scores = bbox_confidences[start:end]

Optionally pass `--write-frame-hdf5` to also write ATM-style per-frame hdf5
files containing datasets named `bboxes` and `confidences`.
"""

from __future__ import annotations

import argparse
import importlib
import json
import os
import re
import sys
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

import cv2
import imageio.v2 as iio_v2
import imageio.v3 as iio
import numpy as np
from PIL import Image
from tqdm import tqdm

try:
    from atm_bbox_prompts import get_task_to_prompt_dict
except ModuleNotFoundError:
    from scripts.atm_bbox_prompts import get_task_to_prompt_dict


DEFAULT_CAMERA_KEYS = ("observation.images.image", "observation.images.wrist_image")
DEFAULT_AGENTVIEW_CAMERA_KEYS = ("observation.images.image",)
BBOX_COLOR = (80, 220, 120)

REPO_ROOT = Path(__file__).resolve().parents[1]
LOCAL_GROUNDING_DINO_BUNDLE_ROOT = REPO_ROOT / "third_party" / "grounding_dino_torch27"
LOCAL_GROUNDING_DINO_PACKAGE = LOCAL_GROUNDING_DINO_BUNDLE_ROOT / "grounding_dino"
DEFAULT_GROUNDING_DINO_CONFIG = (
    LOCAL_GROUNDING_DINO_PACKAGE
    / "groundingdino"
    / "config"
    / "GroundingDINO_SwinT_OGC.py"
)
DEFAULT_GROUNDING_DINO_CHECKPOINT = (
    LOCAL_GROUNDING_DINO_BUNDLE_ROOT
    / "gdino_checkpoints"
    / "groundingdino_swint_ogc.pth"
)


@dataclass(frozen=True)
class EpisodeRecord:
    suite: str
    suite_root: Path
    episode_index: int
    task: str
    length: int


@dataclass(frozen=True)
class PromptResolution:
    suite_key: str
    task_key: str | None
    prompt: str
    source: str


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def resolve_data_root(path: str) -> Path:
    root = Path(path)
    if root.exists():
        return root

    alt = Path(str(root).replace("libero_mujuco3.3.2", "libero_mujoco3.3.2"))
    if alt.exists():
        warnings.warn(f"Data root {root} does not exist; using {alt} instead.")
        return alt

    raise FileNotFoundError(
        f"LIBERO data root not found: {root}. "
        "The FastWAM configs use ./data/libero_mujoco3.3.2."
    )


def discover_suite_roots(data_root: Path, suite_names: list[str] | None) -> list[Path]:
    if suite_names:
        roots = []
        for name in suite_names:
            p = data_root / name
            if not p.exists() and not name.endswith("_lerobot"):
                p = data_root / f"{name}_no_noops_lerobot"
            if not p.exists():
                raise FileNotFoundError(f"Suite not found under {data_root}: {name}")
            roots.append(p)
        return roots

    roots = sorted(p for p in data_root.glob("*_lerobot") if p.is_dir())
    if not roots:
        raise FileNotFoundError(f"No '*_lerobot' suites found under {data_root}")
    return roots


def iter_episodes(
    suite_roots: Iterable[Path],
    *,
    episode_start: int | None,
    episode_end: int | None,
    max_episodes: int | None,
) -> list[EpisodeRecord]:
    out: list[EpisodeRecord] = []
    for suite_root in suite_roots:
        suite = suite_root.name
        episodes_path = suite_root / "meta" / "episodes.jsonl"
        if not episodes_path.exists():
            raise FileNotFoundError(f"Missing {episodes_path}")

        for row in read_jsonl(episodes_path):
            ep_idx = int(row["episode_index"])
            if episode_start is not None and ep_idx < episode_start:
                continue
            if episode_end is not None and ep_idx >= episode_end:
                continue

            tasks = row.get("tasks") or [""]
            out.append(
                EpisodeRecord(
                    suite=suite,
                    suite_root=suite_root,
                    episode_index=ep_idx,
                    task=str(tasks[0]),
                    length=int(row["length"]),
                )
            )
            if max_episodes is not None and len(out) >= max_episodes:
                return out
    return out


def episode_video_path(suite_root: Path, camera_key: str, episode_index: int) -> Path:
    chunk = episode_index // 1000
    return (
        suite_root
        / "videos"
        / f"chunk-{chunk:03d}"
        / camera_key
        / f"episode_{episode_index:06d}.mp4"
    )


def load_video_rgb(path: Path, *, resize: int | None = 224) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(f"Missing video: {path}")
    errors: list[str] = []
    try:
        frames = iio.imread(path, plugin="FFMPEG")
    except Exception as exc:
        errors.append(f"imageio.v3/FFMPEG: {type(exc).__name__}: {exc}")
        try:
            reader = iio_v2.get_reader(str(path), format="ffmpeg")
            try:
                frames = np.stack([frame for frame in reader], axis=0)
            finally:
                reader.close()
        except Exception as exc:
            errors.append(f"imageio.v2/ffmpeg: {type(exc).__name__}: {exc}")
            try:
                import av

                container = av.open(str(path))
                try:
                    decoded = [frame.to_ndarray(format="rgb24") for frame in container.decode(video=0)]
                finally:
                    container.close()
                if decoded:
                    frames = np.stack(decoded, axis=0)
                else:
                    raise RuntimeError("PyAV decoded no frames")
            except Exception as exc:
                errors.append(f"PyAV: {type(exc).__name__}: {exc}")
                cap = cv2.VideoCapture(str(path))
                if not cap.isOpened():
                    raise ImportError(
                        "Could not decode mp4 with imageio-ffmpeg, PyAV, or OpenCV. "
                        "LIBERO videos in this dataset are AV1 encoded; install a working AV1 decoder "
                        "(for example `pip install av imageio[ffmpeg]`, or a system ffmpeg with libdav1d/libaom), "
                        f"then retry. Video: {path}. Tried backends: {' | '.join(errors)}"
                    )
                decoded = []
                try:
                    while True:
                        ok, bgr = cap.read()
                        if not ok:
                            break
                        decoded.append(cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB))
                finally:
                    cap.release()
                if not decoded:
                    errors.append("OpenCV: opened video but decoded no frames")
                    raise RuntimeError(
                        "Could not decode mp4 frames. LIBERO videos in this dataset are AV1 encoded; "
                        "install a working AV1 decoder (for example `pip install av imageio[ffmpeg]`, "
                        "or a system ffmpeg with libdav1d/libaom), then retry. "
                        f"Video: {path}. Tried backends: {' | '.join(errors)}"
                    )
                frames = np.stack(decoded, axis=0)
    if frames.ndim != 4 or frames.shape[-1] != 3:
        raise ValueError(f"Expected RGB video [T,H,W,3], got {frames.shape} from {path}")
    frames = np.asarray(frames, dtype=np.uint8)
    if resize is not None and (frames.shape[1] != resize or frames.shape[2] != resize):
        frames = np.stack(
            [cv2.resize(f, (resize, resize), interpolation=cv2.INTER_AREA) for f in frames],
            axis=0,
        )
    return frames


def slugify(text: str, max_len: int = 80) -> str:
    text = re.sub(r"[^a-zA-Z0-9._-]+", "_", text.strip().lower())
    text = re.sub(r"_+", "_", text).strip("_")
    return (text or "unknown")[:max_len]


def write_manifest_row(path: Path, row: dict[str, Any]) -> None:
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def write_rgb_video_or_contact_sheet(frames: list[np.ndarray], path: Path, fps: int, *, max_sheet_frames: int = 12) -> None:
    if not frames:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    h, w = frames[0].shape[:2]
    ok = False
    try:
        writer = cv2.VideoWriter(
            str(path),
            cv2.VideoWriter_fourcc(*"mp4v"),
            float(fps),
            (w, h),
        )
        if writer.isOpened():
            for frame in frames:
                writer.write(cv2.cvtColor(frame, cv2.COLOR_RGB2BGR))
            ok = True
        writer.release()
    except Exception as exc:
        warnings.warn(f"Failed to write visualization video {path}: {exc}")

    if ok:
        return

    sheet_path = path.with_suffix(".png")
    select = frames
    if len(select) > max_sheet_frames:
        select = [frames[i] for i in np.linspace(0, len(frames) - 1, max_sheet_frames, dtype=np.int32)]
    cols = min(4, len(select))
    rows = int(np.ceil(len(select) / cols))
    canvas = np.zeros((rows * h, cols * w, 3), dtype=np.uint8)
    for idx, frame in enumerate(select):
        r, c = divmod(idx, cols)
        canvas[r * h : (r + 1) * h, c * w : (c + 1) * w] = frame
    Image.fromarray(canvas).save(sheet_path)


def normalize_suite_key(suite: str) -> str:
    name = suite
    for suffix in ("_no_noops_lerobot", "_lerobot"):
        if name.endswith(suffix):
            name = name[: -len(suffix)]
    if name == "libero_long":
        return "libero_10"
    return name


def task_slug(text: str) -> str:
    text = re.sub(r"[^a-zA-Z0-9]+", "_", text.strip())
    text = re.sub(r"_+", "_", text).strip("_")
    return text


def resolve_task_prompt(
    *,
    suite: str,
    task: str,
    task_to_prompt: dict[str, dict[str, str]],
    allow_fallback: bool,
) -> PromptResolution:
    suite_key = normalize_suite_key(suite)
    suite_prompts = task_to_prompt.get(suite_key)
    if not suite_prompts:
        if allow_fallback:
            return PromptResolution(suite_key, None, task, "episode_task_fallback")
        raise KeyError(f"No ATM prompt dictionary entry for suite: {suite} -> {suite_key}")

    slug = task_slug(task)
    exact_key = f"{slug}_demo"
    if exact_key in suite_prompts:
        return PromptResolution(suite_key, exact_key, suite_prompts[exact_key], "atm_prompt_exact")

    suffix = f"_{slug}_demo"
    matches = [k for k in suite_prompts if k.endswith(suffix)]
    if len(matches) == 1:
        key = matches[0]
        return PromptResolution(suite_key, key, suite_prompts[key], "atm_prompt_suffix")

    compact_slug = slug.lower()
    compact_matches = [k for k in suite_prompts if compact_slug in k.lower().removesuffix("_demo")]
    if len(compact_matches) == 1:
        key = compact_matches[0]
        return PromptResolution(suite_key, key, suite_prompts[key], "atm_prompt_contains")

    if allow_fallback:
        return PromptResolution(suite_key, None, task, "episode_task_fallback")

    candidates = ", ".join(sorted(suite_prompts)[:8])
    raise KeyError(
        f"Could not resolve ATM prompt for suite={suite_key!r}, task={task!r}. "
        f"First prompt keys: {candidates}"
    )


def camera_uses_agentview_prompt(camera_key: str, agentview_camera_keys: set[str]) -> bool:
    if camera_key in agentview_camera_keys:
        return True
    return "agentview" in camera_key.lower()


def prompt_for_camera(task_prompt: str, camera_key: str, agentview_camera_keys: set[str]) -> str:
    if camera_uses_agentview_prompt(camera_key, agentview_camera_keys):
        return "the robotic arm. " + task_prompt
    return task_prompt


def prepare_grounding_dino_paths() -> None:
    paths = [LOCAL_GROUNDING_DINO_PACKAGE, LOCAL_GROUNDING_DINO_BUNDLE_ROOT]
    for path in reversed(paths):
        if not path.exists():
            continue
        s = str(path.resolve())
        if s in sys.path:
            sys.path.remove(s)
        sys.path.insert(0, s)


def use_local_hf_cache_if_available(model_id: str) -> None:
    cache_name = f"models--{model_id.replace('/', '--')}"
    cache_roots = [
        Path(os.environ["HF_HUB_CACHE"]).expanduser() if os.environ.get("HF_HUB_CACHE") else None,
        Path(os.environ["HF_HOME"]).expanduser() / "hub" if os.environ.get("HF_HOME") else None,
        Path.home() / ".cache" / "huggingface" / "hub",
    ]
    if any(root is not None and (root / cache_name).exists() for root in cache_roots):
        os.environ.setdefault("HF_HUB_OFFLINE", "1")
        os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")


def groundingdino_cuda_extension_available() -> tuple[bool, str]:
    prepare_grounding_dino_paths()
    try:
        import torch  # noqa: F401

        importlib.import_module("grounding_dino.groundingdino._C")
        return True, "ok"
    except Exception as exc:
        return False, f"{type(exc).__name__}: {exc}"


def resolve_runtime_device(requested_device: str) -> str:
    if str(requested_device).startswith("cuda"):
        try:
            import torch
        except Exception:
            return requested_device
        if not torch.cuda.is_available():
            print(f"[BBOX] requested device={requested_device}, but CUDA is not available; falling back to cpu.")
            return "cpu"
        ok, reason = groundingdino_cuda_extension_available()
        if not ok:
            print(
                "[BBOX] requested CUDA, but the local GroundingDINO CUDA extension is not usable; "
                f"falling back to cpu. Reason: {reason}"
            )
            return "cpu"
    return requested_device


def empty_boxes() -> np.ndarray:
    return np.zeros((0, 4), dtype=np.float32)


def empty_confidences() -> np.ndarray:
    return np.zeros((0,), dtype=np.float32)


class ImagePreprocessorForGroundingModel:
    def __init__(self, out_image_size: int = 800) -> None:
        import torchvision.transforms as T

        self._transform = T.Compose(
            [
                T.Resize((out_image_size, out_image_size)),
                T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
            ]
        )

    def process(self, images):
        return self._transform(images / 255.0).contiguous()


class LocalGroundingDinoBBoxAnnotator:
    def __init__(
        self,
        *,
        config_path: Path,
        checkpoint_path: Path,
        device: str,
        batch_size: int,
        box_threshold: float,
        text_threshold: float,
        agentview_camera_keys: set[str],
        allow_prompt_fallback: bool,
    ):
        if not config_path.exists():
            raise FileNotFoundError(f"Missing local GroundingDINO config: {config_path}")
        if not checkpoint_path.exists():
            raise FileNotFoundError(f"Missing local GroundingDINO checkpoint: {checkpoint_path}")

        prepare_grounding_dino_paths()
        use_local_hf_cache_if_available("bert-base-uncased")

        from grounding_dino.groundingdino.util.inference import load_model

        self.device = device
        self.batch_size = batch_size
        self.box_threshold = box_threshold
        self.text_threshold = text_threshold
        self.agentview_camera_keys = agentview_camera_keys
        self.allow_prompt_fallback = allow_prompt_fallback
        self.task_to_prompt = get_task_to_prompt_dict()
        self.detector = load_model(
            model_config_path=str(config_path),
            model_checkpoint_path=str(checkpoint_path),
            device=device,
        ).to(device)
        self.detector.eval()
        for param in self.detector.parameters():
            param.requires_grad = False
        self.tokenizer = self.detector.tokenizer
        self.img_preprocessor_for_detector = ImagePreprocessorForGroundingModel(out_image_size=800)

    def resolve_prompt(self, suite: str, task: str) -> PromptResolution:
        return resolve_task_prompt(
            suite=suite,
            task=task,
            task_to_prompt=self.task_to_prompt,
            allow_fallback=self.allow_prompt_fallback,
        )

    def detect_objects(
        self,
        images,
        text_prompts: list[str],
    ) -> tuple[list[Any], list[Any], list[list[str]]]:
        import torch
        from grounding_dino.groundingdino.util.inference import preprocess_caption
        from grounding_dino.groundingdino.util.utils import get_phrases_from_posmap

        processed_captions = [preprocess_caption(text_prompt) for text_prompt in text_prompts]
        processed_images = self.img_preprocessor_for_detector.process(images)
        with torch.no_grad():
            outputs = self.detector(processed_images, captions=processed_captions)

        prediction_logits = outputs["pred_logits"].cpu().sigmoid()
        prediction_boxes = outputs["pred_boxes"].cpu()
        batch_boxes, batch_logits, batch_phrases = [], [], []

        for i in range(prediction_logits.shape[0]):
            logits = prediction_logits[i]
            boxes = prediction_boxes[i]
            mask = logits.max(dim=1)[0] > self.box_threshold
            filtered_logits = logits[mask]
            filtered_boxes = boxes[mask]
            tokenized = self.tokenizer(processed_captions[i])
            phrases = [
                get_phrases_from_posmap(logit > self.text_threshold, tokenized, self.tokenizer).replace(".", "")
                for logit in filtered_logits
            ]
            batch_boxes.append(filtered_boxes)
            batch_logits.append(filtered_logits.max(dim=1)[0])
            batch_phrases.append(phrases)
        return batch_boxes, batch_logits, batch_phrases

    def annotate(
        self,
        *,
        frames: np.ndarray,
        frame_indices: np.ndarray,
        task_prompt: str,
        camera_key: str,
    ) -> tuple[list[np.ndarray], list[np.ndarray], list[list[str]]]:
        import torch
        from torchvision.ops import box_convert

        selected = frames[frame_indices]
        prompt = prompt_for_camera(task_prompt, camera_key, self.agentview_camera_keys)
        boxes_out: list[np.ndarray] = []
        confs_out: list[np.ndarray] = []
        labels_out: list[list[str]] = []

        for start in range(0, len(selected), self.batch_size):
            batch = selected[start : start + self.batch_size]
            images = torch.from_numpy(batch).permute(0, 3, 1, 2).float().to(self.device)
            prompts = [prompt] * len(batch)
            batch_boxes, batch_confidences, batch_labels = self.detect_objects(images, prompts)

            _, _, h, w = images.shape
            scale = torch.tensor([w, h, w, h], dtype=torch.float32)
            for boxes, confidences, labels in zip(batch_boxes, batch_confidences, batch_labels, strict=True):
                if len(boxes):
                    boxes_arr = box_convert(boxes=boxes * scale, in_fmt="cxcywh", out_fmt="xyxy").numpy()
                else:
                    boxes_arr = empty_boxes()
                conf_arr = np.asarray(confidences, dtype=np.float32).reshape(-1)
                if len(conf_arr) != len(boxes_arr):
                    conf_arr = conf_arr[: len(boxes_arr)]
                boxes_out.append(np.asarray(boxes_arr, dtype=np.float32).reshape(-1, 4))
                confs_out.append(conf_arr if len(conf_arr) else empty_confidences())
                labels_out.append([str(x) for x in labels])

        return boxes_out, confs_out, labels_out


def pack_bbox_records(
    boxes_all: list[list[np.ndarray]],
    confidences_all: list[list[np.ndarray]],
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    num_cameras = len(boxes_all)
    num_frames = len(boxes_all[0]) if boxes_all else 0
    offsets = np.zeros((num_cameras, num_frames + 1), dtype=np.int64)
    counts = np.zeros((num_cameras, num_frames), dtype=np.int32)
    flat_boxes: list[np.ndarray] = []
    flat_confidences: list[np.ndarray] = []
    cursor = 0

    for cam_idx, (camera_boxes, camera_confidences) in enumerate(zip(boxes_all, confidences_all, strict=True)):
        offsets[cam_idx, 0] = cursor
        for frame_idx, (boxes, confidences) in enumerate(zip(camera_boxes, camera_confidences, strict=True)):
            boxes = np.asarray(boxes, dtype=np.float32).reshape(-1, 4)
            confidences = np.asarray(confidences, dtype=np.float32).reshape(-1)
            if len(confidences) != len(boxes):
                confidences = confidences[: len(boxes)]
            if len(boxes):
                flat_boxes.append(boxes)
                flat_confidences.append(confidences)
            cursor += len(boxes)
            counts[cam_idx, frame_idx] = len(boxes)
            offsets[cam_idx, frame_idx + 1] = cursor

    if flat_boxes:
        bbox_xyxy = np.concatenate(flat_boxes, axis=0).astype(np.float32)
        bbox_confidences = np.concatenate(flat_confidences, axis=0).astype(np.float32)
    else:
        bbox_xyxy = empty_boxes()
        bbox_confidences = empty_confidences()
    return bbox_xyxy, bbox_confidences, offsets, counts


def save_bboxes_to_hdf5(output_file: Path, bboxes: np.ndarray, confidences: np.ndarray) -> None:
    import h5py

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with h5py.File(output_file, "w") as f:
        f.create_dataset("bboxes", data=np.asarray(bboxes, dtype=np.float32))
        f.create_dataset("confidences", data=np.asarray(confidences, dtype=np.float32))


def camera_file_prefix(camera_key: str) -> str:
    if camera_key == "observation.images.image":
        return "agentview"
    if camera_key == "observation.images.wrist_image":
        return "eye_in_hand"
    return slugify(camera_key)


def save_frame_hdf5_labels(
    *,
    root: Path,
    suite: str,
    task_key: str,
    episode_index: int,
    camera_keys: tuple[str, ...],
    frame_indices: np.ndarray,
    boxes_all: list[list[np.ndarray]],
    confidences_all: list[list[np.ndarray]],
) -> None:
    demo_name = f"episode_{episode_index:06d}"
    out_dir = root / normalize_suite_key(suite) / task_key / "bbox" / demo_name
    for cam_idx, camera_key in enumerate(camera_keys):
        prefix = camera_file_prefix(camera_key)
        for local_idx, frame_idx in enumerate(frame_indices):
            save_bboxes_to_hdf5(
                out_dir / f"{prefix}_{int(frame_idx)}.hdf5",
                boxes_all[cam_idx][local_idx],
                confidences_all[cam_idx][local_idx],
            )


def make_bbox_vis_frames(
    frames: np.ndarray,
    boxes: list[np.ndarray],
    confidences: list[np.ndarray],
    labels: list[list[str]],
    frame_indices: np.ndarray,
    keep: np.ndarray,
) -> list[np.ndarray]:
    out: list[np.ndarray] = []
    for local_idx, frame_idx in zip(keep, frame_indices[keep], strict=True):
        frame = frames[int(frame_idx)].copy()
        frame_boxes = np.asarray(boxes[int(local_idx)], dtype=np.float32).reshape(-1, 4)
        frame_conf = np.asarray(confidences[int(local_idx)], dtype=np.float32).reshape(-1)
        frame_labels = labels[int(local_idx)]
        for box_idx, box in enumerate(frame_boxes):
            x1, y1, x2, y2 = box.astype(int)
            h, w = frame.shape[:2]
            x1 = int(np.clip(x1, 0, max(w - 1, 0)))
            x2 = int(np.clip(x2, 0, max(w - 1, 0)))
            y1 = int(np.clip(y1, 0, max(h - 1, 0)))
            y2 = int(np.clip(y2, 0, max(h - 1, 0)))
            conf = float(frame_conf[box_idx]) if box_idx < len(frame_conf) else 1.0
            label = frame_labels[box_idx] if box_idx < len(frame_labels) else ""
            text = f"{label} {conf:.2f}".strip()
            cv2.rectangle(frame, (x1, y1), (x2, y2), BBOX_COLOR, 2)
            cv2.putText(
                frame,
                text[:42],
                (x1, max(y1 - 5, 12)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.4,
                BBOX_COLOR,
                1,
                cv2.LINE_AA,
            )
        out.append(frame)
    return out


def save_episode_visualizations(
    *,
    vis_root: Path,
    suite: str,
    task: str,
    episode_index: int,
    camera_keys: tuple[str, ...],
    frames_by_camera: list[np.ndarray],
    frame_indices: np.ndarray,
    boxes_all: list[list[np.ndarray]],
    confidences_all: list[list[np.ndarray]],
    labels_all: list[list[list[str]]],
    fps: int,
    max_frames: int,
) -> None:
    task_dir = vis_root / suite / slugify(task) / f"episode_{episode_index:06d}"
    task_dir.mkdir(parents=True, exist_ok=True)
    (task_dir / "task.txt").write_text(task + "\n", encoding="utf-8")

    if max_frames > 0 and len(frame_indices) > max_frames:
        keep = np.linspace(0, len(frame_indices) - 1, max_frames, dtype=np.int32)
    else:
        keep = np.arange(len(frame_indices), dtype=np.int32)

    for cam_idx, camera_key in enumerate(camera_keys):
        cam_dir = task_dir / f"camera_{cam_idx:02d}_{slugify(camera_key)}"
        frames = frames_by_camera[cam_idx]
        write_rgb_video_or_contact_sheet(
            make_bbox_vis_frames(
                frames,
                boxes_all[cam_idx],
                confidences_all[cam_idx],
                labels_all[cam_idx],
                frame_indices,
                keep,
            ),
            cam_dir / "bbox_map.mp4",
            fps,
        )


def process_episode(
    ep: EpisodeRecord,
    *,
    output_root: Path,
    camera_keys: tuple[str, ...],
    frame_stride: int,
    image_size: int,
    bbox_annotator: LocalGroundingDinoBBoxAnnotator,
    overwrite: bool,
    save_visualization: bool,
    visualization_root: Path,
    visualization_fps: int,
    visualization_max_frames: int,
    write_frame_hdf5: bool,
    frame_hdf5_root: Path,
) -> dict[str, Any]:
    suite_out = output_root / ep.suite
    suite_out.mkdir(parents=True, exist_ok=True)
    out_path = suite_out / f"episode_{ep.episode_index:06d}.bbox.npz"
    save_cache = overwrite or not out_path.exists()
    if out_path.exists() and not overwrite and not save_visualization:
        return {
            "suite": ep.suite,
            "episode_index": ep.episode_index,
            "task": ep.task,
            "path": str(out_path),
            "status": "skipped_exists",
        }

    prompt_resolution = bbox_annotator.resolve_prompt(ep.suite, ep.task)
    frames_by_camera = [
        load_video_rgb(episode_video_path(ep.suite_root, cam, ep.episode_index), resize=image_size)
        for cam in camera_keys
    ]

    min_len = min(len(x) for x in frames_by_camera)
    if min_len <= 0:
        raise ValueError(f"Empty video for {ep.suite} episode {ep.episode_index}")
    if any(len(x) != min_len for x in frames_by_camera):
        frames_by_camera = [x[:min_len] for x in frames_by_camera]

    frame_indices = np.arange(0, min_len, frame_stride, dtype=np.int32)

    boxes_all: list[list[np.ndarray]] = []
    confidences_all: list[list[np.ndarray]] = []
    labels_all: list[list[list[str]]] = []

    desc = f"{ep.suite}/ep{ep.episode_index:06d} cameras"
    for cam_idx, frames in enumerate(tqdm(frames_by_camera, desc=desc, leave=False)):
        camera_key = camera_keys[cam_idx]
        boxes, confidences, labels = bbox_annotator.annotate(
            frames=frames,
            frame_indices=frame_indices,
            task_prompt=prompt_resolution.prompt,
            camera_key=camera_key,
        )
        boxes_all.append(boxes)
        confidences_all.append(confidences)
        labels_all.append(labels)

    bbox_xyxy, bbox_confidences, bbox_offsets, bbox_counts = pack_bbox_records(boxes_all, confidences_all)
    label_lists = [
        labels_all[cam_idx][frame_idx]
        for cam_idx in range(len(labels_all))
        for frame_idx in range(len(labels_all[cam_idx]))
    ]

    meta = {
        "schema_version": "fastwam_bbox_v2_episode_labels",
        "suite": ep.suite,
        "suite_key": prompt_resolution.suite_key,
        "episode_index": ep.episode_index,
        "task": ep.task,
        "task_key": prompt_resolution.task_key,
        "task_prompt": prompt_resolution.prompt,
        "task_prompt_source": prompt_resolution.source,
        "camera_keys": camera_keys,
        "agentview_camera_keys": sorted(bbox_annotator.agentview_camera_keys),
        "image_size": image_size,
        "frame_stride": frame_stride,
        "bbox_convention": "xyxy pixel coordinates over the resized per-camera teacher image",
        "bbox_label_source": "local GroundingDINO detector following ATM bbox-only logic",
        "box_threshold": bbox_annotator.box_threshold,
        "text_threshold": bbox_annotator.text_threshold,
    }

    if save_cache:
        np.savez_compressed(
            out_path,
            frame_indices=frame_indices,
            camera_keys=np.asarray(camera_keys),
            bbox_xyxy=bbox_xyxy.astype(np.float32),
            bbox_confidences=bbox_confidences.astype(np.float32),
            bbox_offsets=bbox_offsets.astype(np.int64),
            bbox_counts=bbox_counts.astype(np.int32),
            bbox_labels_json=np.asarray(json.dumps(label_lists, ensure_ascii=False)),
            meta_json=np.asarray(json.dumps(meta, ensure_ascii=False)),
        )

    if write_frame_hdf5:
        task_key = prompt_resolution.task_key or slugify(ep.task)
        save_frame_hdf5_labels(
            root=frame_hdf5_root,
            suite=ep.suite,
            task_key=task_key,
            episode_index=ep.episode_index,
            camera_keys=camera_keys,
            frame_indices=frame_indices,
            boxes_all=boxes_all,
            confidences_all=confidences_all,
        )

    if save_visualization:
        save_episode_visualizations(
            vis_root=visualization_root,
            suite=ep.suite,
            task=ep.task,
            episode_index=ep.episode_index,
            camera_keys=camera_keys,
            frames_by_camera=frames_by_camera,
            frame_indices=frame_indices,
            boxes_all=boxes_all,
            confidences_all=confidences_all,
            labels_all=labels_all,
            fps=visualization_fps,
            max_frames=visualization_max_frames,
        )

    return {
        "suite": ep.suite,
        "episode_index": ep.episode_index,
        "task": ep.task,
        "task_key": prompt_resolution.task_key,
        "task_prompt_source": prompt_resolution.source,
        "path": str(out_path),
        "status": "ok" if save_cache else "visualized_existing",
        "num_frames": int(min_len),
        "num_frame_labels": int(len(frame_indices)),
        "num_bboxes": int(len(bbox_xyxy)),
        "visualization_saved": bool(save_visualization),
    }


def build_argparser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("--data-root", default="./data/libero_mujoco3.3.2")
    parser.add_argument("--output-root", default="./data/libero_mujoco3.3.2_bbox_cache")
    parser.add_argument("--suites", nargs="*", default=None, help="Suite directories or short names. Default: all *_lerobot.")
    parser.add_argument("--camera-keys", nargs="+", default=list(DEFAULT_CAMERA_KEYS))
    parser.add_argument("--episode-start", type=int, default=None)
    parser.add_argument("--episode-end", type=int, default=None)
    parser.add_argument("--max-episodes", type=int, default=None)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--device", default="cuda")

    parser.add_argument("--grounding-dino-config", default=str(DEFAULT_GROUNDING_DINO_CONFIG))
    parser.add_argument("--grounding-dino-checkpoint", default=str(DEFAULT_GROUNDING_DINO_CHECKPOINT))
    parser.add_argument("--bbox-batch-size", type=int, default=1, help="GroundingDINO bbox inference batch size.")
    parser.add_argument("--box-threshold", type=float, default=0.35)
    parser.add_argument("--text-threshold", type=float, default=0.25)
    parser.add_argument(
        "--agentview-camera-keys",
        nargs="*",
        default=list(DEFAULT_AGENTVIEW_CAMERA_KEYS),
        help="Camera keys that receive ATM's 'the robotic arm. ' prompt prefix.",
    )
    parser.add_argument(
        "--allow-prompt-fallback",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Fall back to the episode task text if the local ATM prompt dictionary has no unique match.",
    )

    parser.add_argument("--image-size", type=int, default=224, help="Per-camera teacher input resolution.")
    parser.add_argument("--frame-stride", type=int, default=1, help="BBox frame stride. Use 1 for full coverage.")

    parser.add_argument(
        "--write-frame-hdf5",
        action="store_true",
        help="Also write ATM-style per-frame hdf5 files with bboxes/confidences datasets.",
    )
    parser.add_argument("--frame-hdf5-root", default="./bbox_data", help="Root for --write-frame-hdf5 outputs.")

    parser.add_argument("--vis-num-demos-per-task", type=int, default=1)
    parser.add_argument("--vis-output-dir", default=None)
    parser.add_argument("--vis-fps", type=int, default=10)
    parser.add_argument("--vis-max-frames", type=int, default=48)
    return parser


def main() -> None:
    args = build_argparser().parse_args()
    if args.frame_stride < 1:
        raise ValueError("--frame-stride must be >= 1")
    if args.bbox_batch_size < 1:
        raise ValueError("--bbox-batch-size must be a positive integer")
    if args.vis_num_demos_per_task < 0:
        raise ValueError("--vis-num-demos-per-task must be >= 0")
    if args.vis_fps < 1:
        raise ValueError("--vis-fps must be a positive integer")
    if args.vis_max_frames < 0:
        raise ValueError("--vis-max-frames must be >= 0")
    args.device = resolve_runtime_device(args.device)

    data_root = resolve_data_root(args.data_root)
    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)
    visualization_root = Path(args.vis_output_dir) if args.vis_output_dir else output_root / "visualizations"
    manifest_path = output_root / "manifest.jsonl"
    if args.overwrite and manifest_path.exists():
        manifest_path.unlink()

    suite_roots = discover_suite_roots(data_root, args.suites)
    episodes = iter_episodes(
        suite_roots,
        episode_start=args.episode_start,
        episode_end=args.episode_end,
        max_episodes=args.max_episodes,
    )
    if not episodes:
        raise RuntimeError("No episodes selected.")

    print(f"[BBOX] data_root={data_root}")
    print(f"[BBOX] output_root={output_root}")
    print(f"[BBOX] suites={[p.name for p in suite_roots]}")
    print(f"[BBOX] selected_episodes={len(episodes)}")
    print(f"[BBOX] local_grounding_dino_config={Path(args.grounding_dino_config).resolve()}")
    print(f"[BBOX] local_grounding_dino_checkpoint={Path(args.grounding_dino_checkpoint).resolve()}")
    print(f"[BBOX] device={args.device}")
    print(f"[BBOX] visualizations: first {args.vis_num_demos_per_task} demos/task -> {visualization_root}")

    bbox_annotator = LocalGroundingDinoBBoxAnnotator(
        config_path=Path(args.grounding_dino_config),
        checkpoint_path=Path(args.grounding_dino_checkpoint),
        device=args.device,
        batch_size=args.bbox_batch_size,
        box_threshold=args.box_threshold,
        text_threshold=args.text_threshold,
        agentview_camera_keys=set(args.agentview_camera_keys),
        allow_prompt_fallback=args.allow_prompt_fallback,
    )

    visualization_counts: dict[tuple[str, str], int] = {}
    for ep in tqdm(episodes, desc="episodes"):
        vis_key = (ep.suite, ep.task)
        cur_vis_count = visualization_counts.get(vis_key, 0)
        save_visualization = args.vis_num_demos_per_task > 0 and cur_vis_count < args.vis_num_demos_per_task
        if save_visualization:
            visualization_counts[vis_key] = cur_vis_count + 1

        row = process_episode(
            ep,
            output_root=output_root,
            camera_keys=tuple(args.camera_keys),
            frame_stride=args.frame_stride,
            image_size=args.image_size,
            bbox_annotator=bbox_annotator,
            overwrite=args.overwrite,
            save_visualization=save_visualization,
            visualization_root=visualization_root,
            visualization_fps=args.vis_fps,
            visualization_max_frames=args.vis_max_frames,
            write_frame_hdf5=args.write_frame_hdf5,
            frame_hdf5_root=Path(args.frame_hdf5_root),
        )
        write_manifest_row(manifest_path, row)

    print(f"[BBOX] done. Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
